language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm

before_script:
  - composer self-update

script:
    - composer validate
    - composer install
    - ./vendor/bin/phing sniff
    - ./vendor/bin/phing unit